config/routes.rb
Rails.application.routes.draw do
  get 'giders/index'

  root "static_pages#home"
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :daires,:kisilers,:kasas,:aidats,:giders

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
  
end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
  belongs_to :user
  has_secure_token :remember_token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blok.rb
class Blok < ApplicationRecord
  has_many :daire
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/daire.rb
class Daire < ApplicationRecord
  belongs_to :dairetipi
  belongs_to :blok

end

app/models/dairetipi.rb
class Dairetipi < ApplicationRecord
  has_many :daire
end

app/models/giderkategori.rb
class Giderkategori < ApplicationRecord
end

app/models/kisiler.rb
class Kisiler < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
    PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

    MAILER_FROM_EMAIL = "no-reply@example.com"

    has_secure_password
    has_many :active_sessions, dependent: :destroy
    attr_accessor :current_password

    before_save :downcase_email
    before_save :downcase_unconfirmed_email
  
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
    validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}

  

    

    def confirm!
        if unconfirmed_or_reconfirming?
          if unconfirmed_email.present?
            return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
          end
          update_columns(confirmed_at: Time.current)
        else
          false
        end
      end
    
    def confirmable_email
        if unconfirmed_email.present?
          unconfirmed_email
        else
          email
        end
    end
    
    def unconfirmed_or_reconfirming?
        unconfirmed? || reconfirming?
    end

    def reconfirming?
        unconfirmed_email.present?
    end

    def confirmed?
      confirmed_at.present?
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
    
    def generate_password_reset_token
        signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
    end
    
    def send_password_reset_email!
        password_reset_token = generate_password_reset_token
        UserMailer.password_reset(self, password_reset_token).deliver_now
    end

    def unconfirmed?
      !confirmed?
    end

    def send_confirmation_email!
        confirmation_token = generate_confirmation_token
        UserMailer.confirmation(self, confirmation_token).deliver_now
    end
  
    def self.authenticate_by(attributes)
        passwords, identifiers = attributes.to_h.partition do |name, value|
          !has_attribute?(name) && has_attribute?("#{name}_digest")
        end.map(&:to_h)
    
        raise ArgumentError, "One or more password arguments are required" if passwords.empty?
        raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
        if (record = find_by(identifiers))
          record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
        else
          new(passwords)
          nil
        end
    end  

    private
    
    def downcase_unconfirmed_email
        return if unconfirmed_email.nil?
        self.unconfirmed_email = unconfirmed_email.downcase
    end

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/kasas_controller.rb
class KasasController < ApplicationController
  def index
  end
end

app/controllers/kisilers_controller.rb
class KisilersController < ApplicationController
  def index
    @kisiler=Kisiler.all
  end
  def new
    @kisiler = Kisiler.new
  end
  def edit
    @kisiler = Kisiler.find_by(id: params[:id])
  end
  def show
    @kisi = Kisiler.find_by(id: params[:id])
  end
  def create
    @kisiler = Kisiler.new(kisiler_save_params)
    if @kisiler.save
      redirect_to kisilers_path
    else
      render 'index'
    end
  end
  def kisiler_save_params
    params.require(:kisiler).permit(:adsoyad,:telefon,:eposta,:adres,:sifre,:tcno,:dogumtarihi,:meslek)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_authenticated, only: [:create, :new]
  before_action :authenticate_user!, only: [:edit, :destroy, :update]

  def create
     @user = User.new(create_user_params)

    if @user.save
    @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email)
  end

end

app/helpers/aidats_helper.rb
module AidatsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/daires_helper.rb
module DairesHelper
end

app/helpers/giders_helper.rb
module GidersHelper
end

app/helpers/kasas_helper.rb
module KasasHelper
end

app/helpers/kisilers_helper.rb
module KisilersHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kisilers/edit.html.erb
<div class="py-4">
  <div class="d-flex justify-content-between w-100 flex-wrap">
    <div class="mb-3 mb-lg-0">
      <h1 class="h4">Daire Sakini Kaydı Güncelle</h1>

    </div>
    <div>
      <a href="" class="btn btn-outline-gray"><i class="far fa-question-circle me-1"></i> Yardım </a>
    </div>
  </div>
</div>

<%= form_for @kisiler do |f| %>

  <div class="row">
    <div class="col-12 mb-4">
      <div class="card border-0 shadow components-section">
        <div class="card-body">
          <div class="row mb-4">
            <div class="col-lg-4 col-sm-6">
              <!-- Form -->
              <div class="mb-4">
                <label class="my-1 me-2" for="country">Blok</label>
                <%= f.text_field :adsoyad , class:"form-control ",placeholder:"Ad Soyad",:required => true %>
              </div>
              <div class="mb-4">
                <label for="email">Telefon</label>
                <%= f.text_field :telefon , class:"form-control ",placeholder:"Telefon" %>


              </div>
              <div class="mb-4">
                <label class="my-1 me-2" for="country">E Posta</label>
                <%= f.text_field :eposta , class:"form-control ",placeholder:"E Posta" %>



              </div>
              <div class="mb-4">
                <label for="email">Adres</label>
                <%= f.text_field :adres , class:"form-control ",placeholder:"Adres" %>

              </div>

            </div>
            <div class="col-lg-4 col-sm-6">

              <div class="mb-4">
                <label for="email">Şifre</label>
                <%= f.text_field :sifre , class:"form-control ",placeholder:"Şifre" %>

              </div>
              <div class="mb-4">
                <label for="email">TC No</label>
                <%= f.text_field :tcno , class:"form-control ",placeholder:"TC Kimlik No" %>

              </div>
              <div class="mb-4">
                <label for="email">Doğum Tarihi</label>
                <%= f.date_field :dogumtarihi , class:"form-control "%>

              </div>
              <div class="mb-4">
                <label for="email">Meslek</label>
                <%= f.text_field :meslek , class:"form-control ",placeholder:"Meslek" %>
              </div>
              <div class="mb-4">


              </div>
              <!-- Form -->

            </div>
            <div class="col-lg-4 col-sm-6">

              <!--  Baglı daireler begin  -->

              <div class="card border-0 shadow mb-4">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                      <thead class="thead-light">
                      <tr>
                        <th class="border-0 rounded-start">Bağlı Daireler</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td><a href="#" class="text-primary fw-bold">Kayıt Yok</a>
                          <a href="#" class="text-danger me-3">Ekle</a>
                        </td>

                      </tr>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>



            </div>
          </div>

          <div class="row mb-5 mb-lg-5">
            <div class="col-lg-3 col-md-6">

            </div>
            <div class="col-lg-3 col-sm-6 mt-4 mt-md-0">
              <!-- Radio -->

            </div>
            <div class="col-lg-3 col-sm-6 mt-4 mt-md-0">
              <%= submit_tag "Kaydet", class:"btn btn-pill btn-outline-success"%>
              <button class="btn btn-pill btn-outline-danger" type="button">İptal</button>
            </div>
          </div>
        </div>






      </div>
    </div>
  </div>
  </div>

<% end %>

app/views/kisilers/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
  <div class="d-block mb-4 mb-md-0">

    <h2 class="h4">Apartman Sakinleri</h2>
  </div>
  <div class="btn-toolbar mb-2 mb-md-0"><a href="/kisilers/new" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
    <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
    </svg>
    Yeni Kişi Ekle</a>
    <div class="btn-group ms-2 ms-lg-3">

      <button type="button" class="btn btn-sm btn-outline-gray-600">Dışarı Ver</button>
    </div>
  </div>
</div>
<div class="table-settings mb-4">
  <div class="row justify-content-between align-items-center">
    <div class="col-9 col-lg-8 d-md-flex">
      <div class="input-group me-2 me-lg-3 fmxw-300">
          <span class="input-group-text"><svg class="icon icon-xs" x-description="Heroicon name: solid/search" x
                                              mlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                              aria-hidden="true"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg> </span>
        <input type="text" class="form-control" placeholder="Arama">
      </div>
      <select class="form-select fmxw-200 d-none d-md-inline" aria-label="Message select example 2">
        <option selected="selected">Tamamı</option>
        <option value="1">Ev Sahipleri</option>
        <option value="2">Kiracılar</option>
        <option value="3">Kat Sakini</option>
        <option value="3">Boşta olan</option>
      </select></div>
    <div class="col-3 col-lg-4 d-flex justify-content-end">
      <div class="btn-group">
        <div class="dropdown me-1">
          <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M5 4a1 1 0 00-2 0v7.268a2 2 0 000 3.464V16a1 1 0 102 0v-1.268a2 2 0 000-3.464V4zM11 4a1 1 0 10-2 0v1.268a2 2 0 000 3.464V16a1 1 0 102 0V8.732a2 2 0 000-3.464V4zM16 3a1 1 0 011 1v7.268a2 2 0 010 3.464V16a1 1 0 11-2 0v-1.268a2 2 0 010-3.464V4a1 1 0 011-1z"></path>
            </svg>
            <span class="visually-hidden">Toggle Dropdown</span></button>
          <div class="dropdown-menu dropdown-menu-end pb-0"><span class="small ps-3 fw-bold text-dark">Göster</span>
            <a class="dropdown-item d-flex align-items-center fw-bold" href="#">10
              <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
              </svg>
            </a><a class="dropdown-item fw-bold" href="#">20</a>
            <a class="dropdown-item fw-bold rounded-bottom" href="#">30</a></div>
        </div>
        <div class="dropdown">
          <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path>
            </svg>
            <span class="visually-hidden">Toggle Dropdown</span></button>
          <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0">
            <span class="small ps-3 fw-bold text-dark">Göster</span>
            <a class="dropdown-item d-flex align-items-center fw-bold" href="#">10
              <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
              </svg>
            </a><a class="dropdown-item fw-bold" href="#">20</a>
            <a class="dropdown-item fw-bold rounded-bottom" href="#">30</a></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="card card-body shadow border-0 table-wrapper table-responsive">
  <div class="d-flex mb-3"><select class="form-select fmxw-200" aria-label="Message select example">
    <option selected="selected">Toplu İşlem</option>
    <option value="1">Borçlandır</option>
    <option value="2">Bilgilendirme Gönder</option>
    <option value="3">Raporla</option>
  </select>
    <button class="btn btn-sm px-3 btn-secondary ms-3">Uygula</button>
  </div>
  <table class="table user-table table-hover align-items-center">
    <thead>
    <tr>
      <th class="border-bottom">
        <div class="form-check dashboard-check">
          <input class="form-check-input" type="checkbox" value="" id="userCheck55">
          <label class="form-check-label" for="userCheck55"></label></div>
      </th>
      <th class="border-bottom">Ad Soyad</th>
      <th class="border-bottom">Hesap Tipi</th>
      <th class="border-bottom">Telefon</th>
      <th class="border-bottom">Bakiye</th>
      <th class="border-bottom">işlemler</th>
    </tr>
    </thead>
    <tbody>

    <% @kisiler.each do |kisilist| %>
    <tr>
      <td>
        <div class="form-check dashboard-check">
          <input class="form-check-input" type="checkbox" value="" id="userCheck<%=kisilist.id %>">
          <label class="form-check-label" for="userCheck2"></label></div>
      </td>
      <td><a href="<%=kisiler_path(kisilist.id) %>" class="d-flex align-items-center">
        <div class="avatar d-flex align-items-center justify-content-center fw-bold rounded bg-secondary me-3">
          <span>YK</span></div>
        <div class="d-block"><span class="fw-bold">
          <%=kisilist.adsoyad %>

        </span>
          <div class="small text-gray"><%=kisilist.eposta %></div>
        </div>
      </a></td>
      <td><span class="fw-normal text-success">Daire Sahibi</span>
        <div class="small text-gray">A Blok No:01</div>
        <span class="fw-normal text-danger">Kiracı</span>
        <div class="small text-gray">A Blok No:05</div>
      </td>
      <td><span class="fw-normal d-flex align-items-center"><svg class="icon icon-xxs text-success me-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
              clip-rule="evenodd"></path></svg> <%=kisilist.telefon %></span>
      </td>
      <td><span class="fw-normal text-danger">-100 TL</span></td>


      <td>
        <div class="btn-group">
          <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path>
            </svg>
            <span class="visually-hidden">Toggle Dropdown</span></button>
          <div class="dropdown-menu dashboard-dropdown dropdown-menu-start mt-2 py-1">
            <a class="dropdown-item d-flex align-items-center" href="#">
              <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 1.944A11.954 11.954 0 012.166 5C2.056 5.649 2 6.319 2 7c0 5.225 3.34 9.67 8 11.317C14.66 16.67 18 12.225 18 7c0-.682-.057-1.35-.166-2.001A11.954 11.954 0 0110 1.944zM11 14a1 1 0 11-2 0 1 1 0 012 0zm0-7a1 1 0 10-2 0v3a1 1 0 102 0V7z" clip-rule="evenodd"></path>
              </svg>
              Reset Pass </a><a class="dropdown-item d-flex align-items-center" href="#">
            <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
              <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path>
            </svg>
            View Details </a><a class="dropdown-item d-flex align-items-center" href="#">
            <svg class="dropdown-icon text-danger me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M11 6a3 3 0 11-6 0 3 3 0 016 0zM14 17a6 6 0 00-12 0h12zM13 8a1 1 0 100 2h4a1 1 0 100-2h-4z"></path>
            </svg>
            Suspend</a></div>
        </div>
        <svg class="icon icon-xs text-danger ms-1" title="" data-bs-toggle="tooltip" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" data-bs-original-title="Delete" aria-label="Delete">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path>
        </svg>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
  <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
    <nav aria-label="Page navigation example">
      <ul class="pagination mb-0">
        <li class="page-item"><a class="page-link" href="#">Geri</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item "><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">4</a></li>
        <li class="page-item"><a class="page-link" href="#">5</a></li>
        <li class="page-item"><a class="page-link" href="#">İleri</a></li>
      </ul>
    </nav>
    <div class="fw-normal small mt-4 mt-lg-0">Toplam <b>15</b> kayıt -gösterilen <b>5</b></div>
  </div>
</div>

eksikler<br>

<lu>
  <li>hesaplar gözükmeli</li>
  <li>Tüm kolonlar aktif olmalı</li>
  <li>Dışarı export</li>
  <li>Filtre</li>
  <li>Arama</li>
  <li>Üzerine tıklayınca kartına gitmeli</li>
</lu>

app/views/kisilers/new.html.erb
<div class="py-4">
  <div class="d-flex justify-content-between w-100 flex-wrap">
    <div class="mb-3 mb-lg-0">
      <h1 class="h4">Daire Sakini Kaydı</h1>

    </div>
    <div>
      <a href="" class="btn btn-outline-gray"><i class="far fa-question-circle me-1"></i> Yardım </a>
    </div>
  </div>
</div>

<%= form_for @kisiler do |f| %>

  <div class="row">
    <div class="col-12 mb-4">
      <div class="card border-0 shadow components-section">
        <div class="card-body">
          <div class="row mb-4">
            <div class="col-lg-4 col-sm-6">
              <!-- Form -->
              <div class="mb-4">
                <label class="my-1 me-2" for="country">Blok</label>
                <%= f.text_field :adsoyad , class:"form-control ",placeholder:"Ad Soyad",:required => true %>
              </div>
              <div class="mb-4">
                <label for="email">Telefon</label>
                <%= f.text_field :telefon , class:"form-control ",placeholder:"Telefon" %>


              </div>
              <div class="mb-4">
                <label class="my-1 me-2" for="country">E Posta</label>
                <%= f.text_field :eposta , class:"form-control ",placeholder:"E Posta" %>



              </div>
              <div class="mb-4">
                <label for="email">Adres</label>
                <%= f.text_field :adres , class:"form-control ",placeholder:"Adres" %>

              </div>

            </div>
            <div class="col-lg-4 col-sm-6">

              <div class="mb-4">
                <label for="email">Şifre</label>
                <%= f.text_field :sifre , class:"form-control ",placeholder:"Şifre" %>

              </div>
              <div class="mb-4">
                <label for="email">TC No</label>
                <%= f.text_field :tcno , class:"form-control ",placeholder:"TC Kimlik No" %>

              </div>
              <div class="mb-4">
                <label for="email">Doğum Tarihi</label>
                <%= f.date_field :dogumtarihi , class:"form-control "%>

              </div>
              <div class="mb-4">
                <label for="email">Meslek</label>
                <%= f.text_field :meslek , class:"form-control ",placeholder:"Meslek" %>
              </div>
              <div class="mb-4">


              </div>
              <!-- Form -->

            </div>
            <div class="col-lg-4 col-sm-6">

                <!--  Baglı daireler begin  -->

              <div class="card border-0 shadow mb-4">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                      <thead class="thead-light">
                      <tr>
                        <th class="border-0 rounded-start">Bağlı Daireler</th>
                        </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td><a href="#" class="text-primary fw-bold">Kayıt Yok</a>
                          <a href="#" class="text-danger me-3">Ekle</a>
                        </td>

                      </tr>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>



            </div>
          </div>

          <div class="row mb-5 mb-lg-5">
            <div class="col-lg-3 col-md-6">

            </div>
            <div class="col-lg-3 col-sm-6 mt-4 mt-md-0">
              <!-- Radio -->

            </div>
            <div class="col-lg-3 col-sm-6 mt-4 mt-md-0">
              <%= submit_tag "Kaydet", class:"btn btn-pill btn-outline-success"%>
              <button class="btn btn-pill btn-outline-danger" type="button">İptal</button>
            </div>
          </div>
        </div>






      </div>
    </div>
  </div>
  </div>

<% end %>